/**
 * GENERATED from composio-next docs/public/data/toolkits.json (1519 toolkits).
 * Rows: [slug, name, category, authSchemesJson, toolCount, scopesJson?]
 */
export const PROVIDER_PRESET_ROWS: readonly (readonly [
  string,
  string,
  string,
  string,
  string,
  ...string[],
])[] = [
  [
    "googlebigquery",
    "Google BigQuery",
    "databases",
    '["OAUTH2","GOOGLE_SERVICE_ACCOUNT"]',
    "63",
    '["https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  ["supabase", "Supabase", "developer tools", '["OAUTH2","API_KEY"]', "129", '["all"]'],
  [
    "hubspot",
    "HubSpot",
    "crm",
    '["OAUTH2","API_KEY"]',
    "245",
    '["account-info.security.read","accounting","cms.domains.read","cms.domains.write","crm.export","crm.import","crm.lists.read","crm.lists.write","crm.objects.companies.read","crm.objects.companies.write","crm.objects.contacts.read","crm.objects.contacts.write","crm.objects.deals.read","crm.objects.deals.write","crm.objects.marketing_events.read","crm.objects.marketing_events.write","crm.objects.owners.read","crm.objects.quotes.read","crm.objects.quotes.write","crm.schemas.companies.read","crm.schemas.companies.write","crm.schemas.contacts.read","crm.schemas.contacts.write","oauth"]',
  ],
  ["canvas", "Canvas", "online courses", '["OAUTH2","API_KEY"]', "574"],
  ["cal", "Cal", "scheduling & booking", '["API_KEY","OAUTH2"]', "175"],
  [
    "shopify",
    "Shopify",
    "ecommerce",
    '["API_KEY","OAUTH2","S2S_OAUTH2"]',
    "407",
    '["read_products","write_products","read_orders","write_orders","read_customers","write_customers","read_inventory","write_inventory","read_fulfillments","write_fulfillments","read_assigned_fulfillment_orders","write_assigned_fulfillment_orders","read_content","write_content","read_themes","write_themes","read_locations","read_shipping","write_shipping","read_gift_cards","write_gift_cards","read_script_tags","write_script_tags","read_marketing_events"]',
  ],
  ["clickup", "ClickUp", "productivity", '["OAUTH2","API_KEY"]', "164"],
  ["stripe", "Stripe", "payment processing", '["API_KEY","OAUTH2"]', "432", '["read_write"]'],
  [
    "klaviyo",
    "Klaviyo",
    "marketing automation",
    '["API_KEY","OAUTH2"]',
    "225",
    '["accounts:read","campaigns:read","campaigns:write","conversations:read","conversations:write","catalogs:read","catalogs:write","coupons:read","coupons:write","coupon-codes:read","coupon-codes:write","data-privacy:read","data-privacy:write","events:read","events:write","flows:read","flows:write","images:read","images:write","lists:read","lists:write","metrics:read","metrics:write","profiles:read"]',
  ],
  [
    "borneo",
    "Borneo",
    "security & identity tools",
    '["API_KEY","OAUTH2"]',
    "153",
    '["openid","email","profile","phone","aws.cognito.signin.user.admin"]',
  ],
  [
    "pipedrive",
    "Pipedrive",
    "crm",
    '["OAUTH2","API_KEY"]',
    "402",
    '["contacts:full","leads:full","mail:full","activities:full","products:full","projects:full"]',
  ],
  [
    "googlesuper",
    "Google Super",
    "file management & storage",
    '["OAUTH2","API_KEY"]',
    "473",
    '["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/documents","https://www.googleapis.com/auth/calendar","https://www.googleapis.com/auth/adwords","https://mail.google.com/","https://www.googleapis.com/auth/userinfo.profile","https://www.googleapis.com/auth/contacts.readonly","https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/presentations","https://www.googleapis.com/auth/analytics.readonly","https://www.googleapis.com/auth/analytics","https://www.googleapis.com/auth/tasks","https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata","https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"]',
  ],
  [
    "pagerduty",
    "PagerDuty",
    "server monitoring",
    '["OAUTH2","API_KEY"]',
    "368",
    '["read","write"]',
  ],
  [
    "launch_darkly",
    "LaunchDarkly",
    "developer tools",
    '["API_KEY","OAUTH2"]',
    "248",
    '["reader","writer","observability","offline_access"]',
  ],
  [
    "contentful",
    "Contentful",
    "developer tools",
    '["OAUTH2","API_KEY"]',
    "124",
    '["content_management_manage"]',
  ],
  [
    "dialpad",
    "Dialpad",
    "communication",
    '["OAUTH2","API_KEY"]',
    "192",
    '["recordings_export","message_content_export","screen_pop","calls:list","fax_message","change_log","offline_access"]',
  ],
  ["crowdin", "Crowdin", "developer tools", '["API_KEY","OAUTH2"]', "231", '["project"]'],
  [
    "databricks",
    "Databricks",
    "developer tools",
    '["OAUTH2","API_KEY"]',
    "427",
    '["all-apis","openid","email","profile","offline_access"]',
  ],
  ["getresponse", "GetResponse", "marketing automation", '["API_KEY","OAUTH2"]', "213"],
  [
    "hugging_face",
    "Hugging Face",
    "artificial intelligence",
    '["API_KEY","OAUTH2"]',
    "135",
    '["openid","profile","email"]',
  ],
  ["vercel", "Vercel", "developer tools", '["OAUTH2","API_KEY"]', "146"],
  ["wix", "Wix", "website builders", '["OAUTH2","API_KEY"]', "144"],
  [
    "daytona",
    "Daytona",
    "developer tools",
    '["API_KEY","OAUTH2"]',
    "114",
    '["openid","profile","email"]',
  ],
  ["capsule_crm", "Capsule CRM", "crm", '["OAUTH2","API_KEY"]', "109", '["read","write"]'],
  [
    "datadog",
    "Datadog",
    "server monitoring",
    '["OAUTH2","API_KEY","BEARER_TOKEN"]',
    "65",
    '["dashboards_read","dashboards_write","monitors_read","monitors_write","metrics_read","timeseries_query","events_read","logs_read_data","users_read","incidents_read"]',
  ],
  [
    "jira",
    "Jira",
    "project management",
    '["OAUTH2","S2S_OAUTH2","API_KEY"]',
    "102",
    '["read:jira-work","write:jira-work","manage:jira-project","manage:jira-configuration","read:jira-user","manage:jira-webhook","manage:jira-data-provider","read:servicedesk-request","manage:servicedesk-customer","write:servicedesk-request","read:servicemanagement-insight-objects","offline_access","read:sprint:jira-software","write:sprint:jira-software","read:board-scope:jira-software","write:board-scope:jira-software","read:project:jira","read:issue-type-scheme:jira"]',
  ],
  [
    "alpaca",
    "Alpaca",
    "commerce",
    '["API_KEY","OAUTH2"]',
    "100",
    '["account:write","trading","data"]',
  ],
  [
    "productboard",
    "Productboard",
    "product management",
    '["API_KEY","OAUTH2"]',
    "99",
    '["product_hierarchy_data:read","product_hierarchy_data:create","product_hierarchy_data:manage","custom_fields:read","releases:read","releases:create","releases:manage","notes:read","notes:create","users:read","users:manage","users_pii:read","members_pii:read","plugin_integrations:manage","objectives:read","objectives:create","objectives:manage","key_results:read","key_results:create","key_results:manage","initiatives:read","initiatives:create","initiatives:manage","feedback_form_configurations:read"]',
  ],
  ["follow_up_boss", "Follow Up Boss", "crm", '["API_KEY","OAUTH2"]', "99"],
  ["shippo", "Shippo", "ecommerce", '["API_KEY","OAUTH2"]', "95", '["*"]'],
  [
    "brex",
    "Brex",
    "accounting",
    '["OAUTH2","API_KEY"]',
    "84",
    '["accounts.card.readonly","accounts.cash.readonly","budgets","budgets.readonly","cards","cards.pan","cards.readonly","cash.accounts.readonly","companies.readonly","departments","departments.readonly","expenses.card","expenses.card.readonly","incoming_transfers","linked_accounts.readonly","locations","locations.readonly","offline_access","openid","statements.card.readonly","statements.cash.readonly","titles","titles.readonly","transactions.card.readonly"]',
  ],
  ["clockify", "Clockify", "time tracking software", '["API_KEY","OAUTH2"]', "75"],
  [
    "confluence",
    "Confluence",
    "team collaboration",
    '["OAUTH2","S2S_OAUTH2","API_KEY"]',
    "69",
    '["write:content:confluence","delete:content:confluence","read:space-details:confluence","read:audit-log:confluence","read:page:confluence","write:page:confluence","delete:page:confluence","read:blogpost:confluence","delete:blogpost:confluence","read:whiteboard:confluence","write:whiteboard:confluence","read:comment:confluence","write:comment:confluence","read:content.restriction:confluence","write:content.restriction:confluence","read:content.metadata:confluence","read:inlinetask:confluence","write:inlinetask:confluence","read:task:confluence","write:task:confluence","offline_access"]',
  ],
  [
    "lever",
    "Lever",
    "hr talent & recruitment",
    '["API_KEY","OAUTH2"]',
    "64",
    '["files:write:admin","form_templates:write:admin","forms:write:admin","interviews:write:admin","notes:write:admin","offers:read:admin","opportunities:write:admin","panels:write:admin","postings:write:admin","referrals:read:admin","requisition_fields:write:admin","requisitions:write:admin","resumes:read:admin","sources:read:admin","stages:read:admin","tags:read:admin","tasks:read:admin","uploads:write:admin","users:write:admin"]',
  ],
  [
    "webflow",
    "Webflow",
    "website builders",
    '["OAUTH2","API_KEY"]',
    "60",
    '["assets:read","assets:write","authorized_user:read","cms:read","cms:write","custom_code:read","custom_code:write","forms:read","forms:write","pages:read","pages:write","sites:read","sites:write"]',
  ],
  ["notion", "Notion", "notes", '["OAUTH2","API_KEY"]', "56"],
  [
    "whatsapp",
    "WhatsApp",
    "phone & sms",
    '["OAUTH2","API_KEY"]',
    "57",
    '["whatsapp_business_management","whatsapp_business_messaging","business_management"]',
  ],
  [
    "metaads",
    "Meta Ads",
    "ads & conversion",
    '["OAUTH2","API_KEY"]',
    "56",
    '["ads_read","ads_management","business_management"]',
  ],
  [
    "dropbox_sign",
    "Dropbox Sign",
    "signatures",
    '["API_KEY","OAUTH2"]',
    "56",
    '["basic_account_info","request_signature"]',
  ],
  [
    "railway",
    "Railway",
    "developer tools",
    '["API_KEY","OAUTH2"]',
    "59",
    '["openid","email","profile","offline_access","workspace:viewer","project:viewer"]',
  ],
  [
    "figma",
    "Figma",
    "images & design",
    '["OAUTH2","API_KEY"]',
    "53",
    '["file_comments:write","webhooks:write","current_user:read","file_content:read","file_comments:read","projects:read","library_assets:read","library_content:read","team_library_content:read","file_metadata:read","file_versions:read","webhooks:read"]',
  ],
  ["digital_ocean", "DigitalOcean", "developer tools", '["API_KEY","OAUTH2"]', "48", '["read"]'],
  ["pinecone", "Pinecone", "artificial intelligence", '["API_KEY","OAUTH2"]', "48"],
  [
    "linear",
    "Linear",
    "project management",
    '["OAUTH2","API_KEY"]',
    "47",
    '["read","write","issues:create","comments:create"]',
  ],
  [
    "github",
    "GitHub",
    "developer tools",
    '["OAUTH2"]',
    "893",
    '["repo","user","gist","notifications","project","workflow","codespace"]',
  ],
  [
    "slack",
    "Slack",
    "team chat",
    '["OAUTH2"]',
    "167",
    '["calls:read","calls:write","channels:history","channels:read","channels:write","chat:write","dnd:read","dnd:write","emoji:read","files:read","files:write","groups:history","groups:read","groups:write","im:history","im:read","im:write","links:read","links:write","lists:read","lists:write","mpim:history","mpim:read","mpim:write"]',
  ],
  [
    "outlook",
    "Outlook",
    "email",
    '["OAUTH2","S2S_OAUTH2"]',
    "305",
    '["Calendars.Read","Calendars.ReadWrite","Calendars.ReadWrite.Shared","Contacts.ReadWrite","Chat.ReadWrite","Mail.Read","Mail.ReadWrite","Mail.Send","MailboxSettings.Read","MailboxSettings.ReadWrite","offline_access","User.Read"]',
  ],
  [
    "wrike",
    "Wrike",
    "project management",
    '["OAUTH2"]',
    "144",
    '["Default","wsReadOnly","wsReadWrite","amReadOnlyWorkflow","amReadWriteWorkflow","amReadOnlyInvitation","amReadWriteInvitation","amReadOnlyGroup","amReadWriteGroup","amReadOnlyUser","amReadWriteUser"]',
  ],
  [
    "sentry",
    "Sentry",
    "developer tools",
    '["OAUTH2"]',
    "211",
    '["org:read","org:write","project:read","project:write","project:releases","team:read","team:write","member:read","member:write","event:read","event:write"]',
  ],
  [
    "microsoft_teams",
    "Microsoft Teams",
    "team chat",
    '["OAUTH2","S2S_OAUTH2"]',
    "173",
    '["Channel.Create","Channel.ReadBasic.All","ChannelMessage.Read.All","ChannelMessage.ReadWrite","ChannelMessage.Send","ChannelSettings.ReadWrite.All","Chat.Create","Chat.Read","Chat.ReadBasic","Chat.ReadWrite","Chat.ReadWrite.All","ChatMessage.Read","ChatMessage.Send","Directory.ReadWrite.All","Group.ReadWrite.All","offline_access","People.Read.All","Presence.ReadWrite","Team.Create","Team.ReadBasic.All","TeamMember.ReadWrite.All","TeamsActivity.Read","TeamsActivity.Send","User.Read"]',
  ],
  ["asana", "Asana", "project management", '["OAUTH2"]', "153"],
  ["docusign", "DocuSign", "signatures", '["OAUTH2"]', "338", '["signature","impersonation"]'],
  [
    "discordbot",
    "Discord Bot",
    "team chat",
    '["OAUTH2"]',
    "165",
    '["identify","email","bot","messages.read"]',
  ],
  [
    "salesforce",
    "Salesforce",
    "crm",
    '["OAUTH2","S2S_OAUTH2"]',
    "223",
    '["full","refresh_token","openid"]',
  ],
  ["mailchimp", "Mailchimp", "email newsletters", '["OAUTH2"]', "275"],
  [
    "dropbox",
    "Dropbox",
    "file management & storage",
    '["OAUTH2"]',
    "177",
    '["email","profile","account_info.write","account_info.read","files.metadata.write","files.metadata.read","files.content.write","files.content.read","openid","file_requests.write","file_requests.read","sharing.write","sharing.read","contacts.write","contacts.read"]',
  ],
  [
    "ahrefs",
    "Ahrefs",
    "marketing automation",
    '["API_KEY","OAUTH2"]',
    "40",
    '["apiv3-integration-apps"]',
  ],
  ["monday", "Monday", "project management", '["OAUTH2"]', "125"],
  [
    "bamboohr",
    "BambooHR",
    "human resources",
    '["OAUTH2","API_KEY"]',
    "42",
    '["application","application.write","job_opening","job_opening.write","benefit","benefit.write","email","openid","company:administration","company:administration.write","company:info","company_file","company_file.write","data_cleaner","error_management","employee","employee.write","employee:assets","employee:assets.write","employee:compensation","employee:compensation.write","employee:contact","employee:contact.write","employee:custom_fields"]',
  ],
  [
    "zendesk",
    "Zendesk",
    "crm",
    '["OAUTH2"]',
    "452",
    '["read","write","organizations:read","organizations:write","tickets:read","tickets:write","users:read","users:write","webhooks:read","webhooks:write"]',
  ],
  [
    "servicenow",
    "ServiceNow",
    "it operations",
    '["BASIC","OAUTH2","S2S_OAUTH2"]',
    "171",
    '["useraccount"]',
  ],
  ["zoho_books", "Zoho Books", "accounting", '["OAUTH2"]', "265", '["ZohoBooks.fullaccess.all"]'],
  ["box", "Box", "file management & storage", '["OAUTH2"]', "286"],
  ["blackboard", "Blackboard", "education", '["OAUTH2"]', "314"],
  [
    "square",
    "Square",
    "payment processing",
    '["OAUTH2"]',
    "122",
    '["CUSTOMERS_READ","CUSTOMERS_WRITE","MERCHANT_PROFILE_READ","MERCHANT_PROFILE_WRITE"]',
  ],
  [
    "intercom",
    "Intercom",
    "customer support",
    '["OAUTH2"]',
    "133",
    '["read_user","write_user","read_company","write_company","read_conversation","write_conversation","read_admin","write_admin","read_tag","write_tag","read_event","write_event","read_segment","write_segment","read_count","write_count","read_data_attribute","write_data_attribute","read_ticket","write_ticket","read_team","write_team","read_note","write_note"]',
  ],
  [
    "highlevel",
    "Highlevel",
    "marketing automation",
    '["OAUTH2"]',
    "218",
    '["agent-studio.write","agent-studio.readonly","associations.readonly","associations.write","associations/relation.readonly","associations/relation.write","blogs/list.readonly","brand-boards/design-kit.readonly","brandboards.write","businesses.write","calendars.readonly","calendars.write","calendars/events.readonly","calendars/events.write","charges.readonly","contacts.readonly","contacts.write","conversation-ai.readonly","conversations.readonly","conversations.write","conversations/message.readonly","conversations/message.write","emails/builder.readonly","emails/builder.write"]',
  ],
  [
    "zoho_invoice",
    "Zoho Invoice",
    "proposal & invoice management",
    '["OAUTH2"]',
    "137",
    '["ZohoInvoice.contacts.ALL","ZohoInvoice.settings.ALL","ZohoInvoice.estimates.ALL","ZohoInvoice.invoices.ALL","ZohoInvoice.customerpayments.ALL","ZohoInvoice.creditnotes.ALL","ZohoInvoice.projects.ALL","ZohoInvoice.expenses.ALL"]',
  ],
  [
    "stack_exchange",
    "Stack Exchange",
    "developer tools",
    '["OAUTH2"]',
    "121",
    '["no_expiry","read_inbox","private_info"]',
  ],
  ["twitch", "Twitch", "video & audio", '["OAUTH2","S2S_OAUTH2","NO_AUTH"]', "149"],
  ["basecamp", "Basecamp", "project management", '["OAUTH2"]', "142"],
  [
    "coupa",
    "Coupa",
    "accounting",
    '["OAUTH2"]',
    "384",
    '["openid","profile","email","login","offline_access","core.common.read","core.object_translations.read","core.user.read","core.user_group.read","core.integration.read","core.integration.write","core.approval.read","core.approval.write","core.requisition.read","core.requisition.write","core.purchase_order.read","core.purchase_order.write","core.order_header_confirmations.read","core.order_header_confirmations.write","core.item.read","core.catalog.read","core.uom.read","core.supplier.read","core.supplier_sites.read"]',
  ],
  [
    "greenhouse",
    "Greenhouse",
    "hr talent & recruitment",
    '["S2S_OAUTH2","OAUTH2"]',
    "134",
    '["harvest:application_stages:list","harvest:applications:create","harvest:applications:list","harvest:applications:update","harvest:attachments:create","harvest:attachments:list","harvest:candidates:create","harvest:candidates:list","harvest:candidates:update","harvest:demographic_answers:list","harvest:departments:list","harvest:eeoc:list","harvest:interview_kits:list","harvest:interviews:create","harvest:interviews:list","harvest:interviews:update","harvest:job_posts:create","harvest:job_posts:list","harvest:job_posts:update","harvest:jobs:create","harvest:jobs:list","harvest:jobs:update","harvest:offers:create","harvest:offers:list"]',
  ],
  [
    "gusto",
    "Gusto",
    "human resources",
    '["OAUTH2"]',
    "192",
    '["companies:read","employees:read","payrolls:read"]',
  ],
  ["help_scout", "Help Scout", "customer support", '["OAUTH2"]', "129"],
  ["kit", "Kit", "marketing automation", '["OAUTH2","API_KEY"]', "42", '["public"]'],
  [
    "omnisend",
    "Omnisend",
    "marketing automation",
    '["API_KEY","OAUTH2"]',
    "43",
    '["brands.read","brands.write","contacts.read","contacts.write","events.read","events.write","products.read","products.write","campaigns.read","automations.read"]',
  ],
  ["razorpay", "Razorpay", "payment processing", '["API_KEY","OAUTH2"]', "42", '["read_write"]'],
  [
    "sharepoint_graph",
    "SharePoint Graph",
    "documents",
    '["OAUTH2","S2S_OAUTH2"]',
    "162",
    '["Sites.ReadWrite.All","Sites.Manage.All","Sites.FullControl.All","Files.ReadWrite.All","SensitivityLabels.Read.All","offline_access","User.Read"]',
  ],
  [
    "snapchat",
    "Snapchat",
    "marketing",
    '["OAUTH2"]',
    "139",
    '["snapchat-marketing-api","snapchat-offline-conversions-api","snapchat-profile-api"]',
  ],
  ["workday", "Workday", "human resources", '["OAUTH2"]', "567", '["System"]'],
  [
    "gitlab",
    "GitLab",
    "developer tools",
    '["OAUTH2"]',
    "116",
    '["api","read_api","read_user","read_repository","write_repository","profile","email"]',
  ],
  [
    "microsoft_power_bi",
    "Microsoft Power Bi",
    "business intelligence",
    '["OAUTH2"]',
    "116",
    '["https://analysis.windows.net/powerbi/api/Dataset.Read.All","https://analysis.windows.net/powerbi/api/Report.Read.All","https://analysis.windows.net/powerbi/api/Dashboard.Read.All","https://analysis.windows.net/powerbi/api/Workspace.Read.All","https://analysis.windows.net/powerbi/api/Content.Create","https://analysis.windows.net/powerbi/api/Dataflow.Read.All","offline_access"]',
  ],
  [
    "roam",
    "Roam",
    "communication",
    '["API_KEY","OAUTH2"]',
    "39",
    '["groups:read","chat:read","chat:write","chat:send_message","recordings:read","transcript:read","admin:compliance:read"]',
  ],
  [
    "workable",
    "Workable",
    "human resources",
    '["OAUTH2","API_KEY"]',
    "37",
    '["r_account","r_jobs","r_candidates","w_candidates","r_employees"]',
  ],
  [
    "gorgias",
    "Gorgias",
    "crm",
    '["API_KEY","OAUTH2"]',
    "32",
    '["openid","email","profile","offline","account:read","account:write","users:read","users:write","customers:read","customers:write","tickets:read","tickets:write","custom_fields:read","custom_fields:write","events:read","events:write","integrations:read","integrations:write","jobs:read","jobs:write","macros:read","macros:write","rules:read","rules:write"]',
  ],
  [
    "quickbooks",
    "QuickBooks",
    "accounting",
    '["OAUTH2"]',
    "114",
    '["com.intuit.quickbooks.accounting","openid","profile","email","phone","address"]',
  ],
  [
    "bitbucket",
    "Bitbucket",
    "developer tools",
    '["OAUTH2"]',
    "110",
    '["webhook","pullrequest:write","project:admin","runner:write","project:write","snippet:write","team:write","pipeline:variable","repository:delete","repository:admin","account:write","wiki","issue:write"]',
  ],
  [
    "attio",
    "Attio",
    "crm",
    '["OAUTH2"]',
    "109",
    '["task:read-write","object_configuration:read","record_permission:read","user_management:read","list_configuration:read","list_entry:read","comment:read-write"]',
  ],
  ["lodgify", "Lodgify", "scheduling & booking", '["API_KEY","OAUTH2"]', "30"],
  [
    "airtable",
    "Airtable",
    "productivity",
    '["OAUTH2","API_KEY"]',
    "26",
    '["data.records:read","data.records:write","data.recordComments:read","data.recordComments:write","schema.bases:read","schema.bases:write","user.email:read"]',
  ],
  [
    "zoom",
    "Zoom",
    "video conferencing",
    '["OAUTH2"]',
    "105",
    '["contact:read:list_contacts","meeting:read:summary","meeting:read:list_registrants","meeting:read:list_past_participants","meeting:read:list_meetings","meeting:write:meeting","meeting:update:meeting","meeting:write:registrant","meeting:read:meeting","webinar:read:webinar","webinar:read:list_registrants","webinar:read:list_webinars","webinar:read:list_past_participants","webinar:read:participant","webinar:write:registrant","archiving:read:archived_files","archiving:read:list_archived_files","cloud_recording:delete:meeting_transcript","cloud_recording:read:meeting_transcript","cloud_recording:read:list_user_recordings","cloud_recording:read:list_recording_registrants","cloud_recording:read:list_recording_files","user:read:list_collaboration_devices","user:read:collaboration_device"]',
  ],
  [
    "toneden",
    "Toneden",
    "social media marketing",
    '["API_KEY","OAUTH2"]',
    "26",
    '["user","posts","profiles"]',
  ],
  [
    "scheduleonce",
    "Scheduleonce",
    "scheduling & booking",
    '["API_KEY","OAUTH2"]',
    "27",
    '["id","profile","email"]',
  ],
  ["splitwise", "Splitwise", "accounting", '["OAUTH2","API_KEY"]', "27"],
  ["zeplin", "Zeplin", "images & design", '["OAUTH2","API_KEY"]', "24"],
  [
    "slackbot",
    "Slackbot",
    "team chat",
    '["OAUTH2"]',
    "101",
    '["channels:history","chat:write","team:read","channels:read","users:read","reactions:read","reactions:write"]',
  ],
  [
    "google_maps",
    "Google Maps",
    "developer tools",
    '["OAUTH2","API_KEY"]',
    "23",
    '["https://www.googleapis.com/auth/cloud-platform"]',
  ],
  [
    "brevo",
    "Brevo",
    "email newsletters",
    '["API_KEY","OAUTH2"]',
    "21",
    '["account:read","contacts:read","contacts:write","crm:read","crm:write","campaigns.email:read","campaigns.email:write","campaigns.sms:read","campaigns.sms:write","transactional.email:read","transactional.email:write"]',
  ],
  [
    "survey_monkey",
    "SurveyMonkey",
    "forms & surveys",
    '["OAUTH2","API_KEY"]',
    "22",
    '["surveys_read","surveys_write"]',
  ],
  ["moneybird", "Moneybird", "accounting", '["OAUTH2","API_KEY"]', "21", '["sales_invoices"]'],
  ["neo4j", "Neo4J", "developer tools", '["OAUTH2","BASIC","API_KEY","S2S_OAUTH2"]', "21"],
  ["parma", "Parma", "crm", '["OAUTH2","API_KEY"]', "23", '["full"]'],
  [
    "prisma",
    "Prisma",
    "databases",
    '["OAUTH2","API_KEY"]',
    "22",
    '["workspace:admin","offline_access"]',
  ],
  ["recruitee", "Recruitee", "hr talent & recruitment", '["API_KEY","OAUTH2"]', "23"],
  [
    "share_point",
    "SharePoint",
    "documents",
    '["OAUTH2","S2S_OAUTH2"]',
    "98",
    '["https://{{subdomain}}.sharepoint.com/.default","offline_access"]',
  ],
  ["clio_manage", "Clio Manage (US)", "crm", '["OAUTH2"]', "99"],
  ["dart", "Dart", "project management", '["OAUTH2","API_KEY"]', "18", '["read","write"]'],
  [
    "dub",
    "Dub",
    "url shortener",
    '["API_KEY","OAUTH2"]',
    "17",
    '["user.read","links.read","links.write"]',
  ],
  ["tally", "Tally", "forms & surveys", '["API_KEY","OAUTH2"]', "18", '["user","forms"]'],
  [
    "whop",
    "Whop",
    "ecommerce",
    '["API_KEY","OAUTH2"]',
    "19",
    '["member:basic:read","payment:basic:read"]',
  ],
  [
    "eventbrite",
    "Eventbrite",
    "event management",
    '["OAUTH2"]',
    "95",
    '["event:read","event:write","order:read","order:write","attendee:read","attendee:write","user:read","user:write","organizer:read","organizer:write","venue:read","venue:write"]',
  ],
  [
    "constant_contact",
    "Constant Contact",
    "marketing",
    '["OAUTH2"]',
    "93",
    '["account_read","account_update","contact_data","campaign_data","offline_access"]',
  ],
  ["pushbullet", "Pushbullet", "notifications", '["OAUTH2","API_KEY"]', "15", '["everything"]'],
  ["ticketmaster", "Ticketmaster", "event management", '["API_KEY","OAUTH2"]', "15"],
  [
    "googledrive",
    "Google Drive",
    "file management & storage",
    '["OAUTH2"]',
    "90",
    '["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  ["bitly", "Bitly", "url shortener", '["API_KEY","OAUTH2"]', "10"],
  [
    "ramp",
    "Ramp",
    "accounting",
    '["OAUTH2"]',
    "88",
    '["accounting:read","accounting:write","bank_accounts:read","bills:read","bills:write","business:read","cards:read","cards:read_vault","cards:write","cashbacks:read","custom_records:read","custom_records:write","departments:read","departments:write","entities:read","item_receipts:read","leads:read","leads:write","limits:read","limits:write","locations:read","locations:write","memos:read","memos:write"]',
  ],
  [
    "spotify",
    "Spotify",
    "news & lifestyle",
    '["OAUTH2"]',
    "88",
    '["user-read-private","user-read-email","app-remote-control","streaming","user-modify-playback-state","user-read-playback-state","user-read-currently-playing"]',
  ],
  [
    "storyblok",
    "Storyblok",
    "developer tools",
    '["API_KEY","OAUTH2"]',
    "10",
    '["read_content","write_content"]',
  ],
  ["netsuite", "Netsuite", "accounting", '["OAUTH2"]', "86", '["rest_webservices","restlets"]'],
  ["todoist", "Todoist", "task management", '["OAUTH2"]', "84", '["data:read_write"]'],
  ["beeminder", "Beeminder", "task management", '["API_KEY","OAUTH2"]', "5"],
  ["fathom", "Fathom", "ai meeting assistants", '["OAUTH2","API_KEY"]', "7", '["public_api"]'],
  [
    "sendloop",
    "Sendloop",
    "email newsletters",
    '["API_KEY","OAUTH2"]',
    "5",
    '["account.read","list.read","subscriber.read","campaign.read"]',
  ],
  [
    "one_drive",
    "OneDrive",
    "file management & storage",
    '["OAUTH2","S2S_OAUTH2"]',
    "83",
    '["Files.ReadWrite.All","Sites.ReadWrite.All","offline_access"]',
  ],
  [
    "miro",
    "Miro",
    "team collaboration",
    '["OAUTH2"]',
    "81",
    '["boards:export","boards:read","boards:write"]',
  ],
  [
    "onenote",
    "Microsoft OneNote",
    "productivity",
    '["OAUTH2"]',
    "83",
    '["Notes.Read","Notes.ReadWrite","Notes.Create","Notes.Read.All","Notes.ReadWrite.All","Sites.Read.All","Team.ReadBasic.All","offline_access","User.Read"]',
  ],
  [
    "reddit_ads",
    "Reddit Ads",
    "marketing",
    '["OAUTH2"]',
    "83",
    '["identity","adsread","adsedit","adsconversions","history","read"]',
  ],
  [
    "twitter",
    "Twitter",
    "social media accounts",
    '["OAUTH2"]',
    "79",
    '["dm.write","dm.read","mute.read","mute.write","space.read","tweet.write","tweet.read","tweet.moderate.write","users.read","follows.read","follows.write","like.read","like.write","list.read","list.write","block.read","block.write","bookmark.read","bookmark.write","media.write","offline.access"]',
  ],
  ["freeagent", "Freeagent", "accounting", '["OAUTH2"]', "76"],
  [
    "google_analytics",
    "Google Analytics",
    "analytics",
    '["OAUTH2"]',
    "69",
    '["https://www.googleapis.com/auth/analytics.readonly","https://www.googleapis.com/auth/analytics","https://www.googleapis.com/auth/userinfo.profile"]',
  ],
  [
    "gmail",
    "Gmail",
    "email",
    '["OAUTH2"]',
    "63",
    '["https://www.googleapis.com/auth/userinfo.profile","https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/contacts.readonly","https://www.googleapis.com/auth/contacts.other.readonly","https://www.googleapis.com/auth/profile.language.read","https://www.googleapis.com/auth/user.addresses.read","https://www.googleapis.com/auth/user.birthday.read","https://www.googleapis.com/auth/user.emails.read","https://www.googleapis.com/auth/user.phonenumbers.read","https://www.googleapis.com/auth/profile.emails.read","https://mail.google.com/"]',
  ],
  [
    "egnyte",
    "Egnyte",
    "file management & storage",
    '["OAUTH2"]',
    "60",
    '["Egnyte.filesystem","Egnyte.link","Egnyte.user","Egnyte.permission","Egnyte.group","Egnyte.projectfolders","Egnyte.webhooks","Egnyte.launchwebsession","Egnyte.salesforce","Egnyte.audit","Egnyte.search","Egnyte.notification"]',
  ],
  [
    "google_classroom",
    "Google Classroom",
    "education",
    '["OAUTH2"]',
    "62",
    '["https://www.googleapis.com/auth/classroom.courses.readonly","https://www.googleapis.com/auth/classroom.coursework.students","https://www.googleapis.com/auth/classroom.courseworkmaterials","https://www.googleapis.com/auth/classroom.topics","https://www.googleapis.com/auth/classroom.rosters.readonly","https://www.googleapis.com/auth/classroom.announcements","https://www.googleapis.com/auth/classroom.course-work.readonly","https://www.googleapis.com/auth/classroom.student-submissions.students.readonly","https://www.googleapis.com/auth/classroom.student-submissions.me.readonly","https://www.googleapis.com/auth/classroom.coursework.me","https://www.googleapis.com/auth/classroom.announcements.readonly","https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly","https://www.googleapis.com/auth/classroom.topics.readonly","https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly","https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly","https://www.googleapis.com/auth/classroom.push-notifications","https://www.googleapis.com/auth/userinfo.profile","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  ["calendly", "Calendly", "scheduling & booking", '["OAUTH2"]', "56"],
  [
    "zoho",
    "Zoho",
    "crm",
    '["OAUTH2"]',
    "57",
    '["ZohoCRM.modules.ALL","ZohoCRM.settings.ALL","ZohoCRM.notifications.ALL","ZohoCRM.users.ALL"]',
  ],
  [
    "zoho_inventory",
    "Zoho Inventory",
    "accounting",
    '["OAUTH2"]',
    "58",
    '["ZohoInventory.contacts.ALL","ZohoInventory.items.ALL","ZohoInventory.compositeitems.ALL","ZohoInventory.transferorders.ALL","ZohoInventory.salesorders.ALL","ZohoInventory.packages.ALL","ZohoInventory.shipmentorders.ALL","ZohoInventory.invoices.ALL","ZohoInventory.customerpayments.ALL","ZohoInventory.creditnotes.ALL","ZohoInventory.purchaseorders.ALL","ZohoInventory.purchasereceives.ALL","ZohoInventory.bills.ALL","ZohoInventory.settings.READ"]',
  ],
  [
    "gong",
    "Gong",
    "analytics",
    '["BASIC","OAUTH2"]',
    "58",
    '["api:calls:read:transcript","api:provisioning:read","api:workspaces:read","api:meetings:user:delete","api:crm:get-objects","api:data-privacy:delete","api:crm:schema","api:flows:write","api:crm:upload","api:meetings:integration:status","api:calls:read:extensive","api:meetings:user:update","api:integration-settings:write","api:settings:scorecards:read","api:stats:scorecards","api:stats:interaction","api:stats:user-actions","api:crm:integration:delete","api:calls:read:basic","api:calls:read:media-url","api:tasks:read","api:digital-interactions:write","api:crm:integrations:read","api:library:read"]',
  ],
  [
    "harvest",
    "Harvest",
    "time tracking software",
    '["OAUTH2"]',
    "57",
    '["harvest:read","harvest:write"]',
  ],
  [
    "googlesheets",
    "Google Sheets",
    "spreadsheets",
    '["OAUTH2"]',
    "53",
    '["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  [
    "zoho_bigin",
    "Zoho Bigin",
    "crm",
    '["OAUTH2"]',
    "54",
    '["ZohoBigin.modules.ALL","ZohoBigin.users.ALL","ZohoBigin.org.ALL","ZohoBigin.settings.ALL","ZohoBigin.bulk.ALL","ZohoBigin.notifications.ALL"]',
  ],
  ["kommo", "Kommo", "crm", '["OAUTH2"]', "53"],
  [
    "xero",
    "Xero",
    "accounting",
    '["OAUTH2"]',
    "53",
    '["offline_access","email","profile","openid","files","files.read","projects","projects.read","accounting.manualjournals.read","accounting.manualjournals","accounting.banktransactions.read","accounting.banktransactions","accounting.payments.read","accounting.payments","accounting.invoices.read","accounting.invoices","accounting.reports.tenninetynine.read","accounting.budgets.read","accounting.attachments.read","accounting.attachments","accounting.contacts.read","accounting.contacts","accounting.settings.read","accounting.settings"]',
  ],
  [
    "excel",
    "Excel",
    "spreadsheets",
    '["OAUTH2","S2S_OAUTH2"]',
    "54",
    '["Files.ReadWrite","Sites.ReadWrite.All","offline_access","User.Read"]',
  ],
  ["soundcloud", "SoundCloud", "video & audio", '["OAUTH2"]', "52", '["non-expiring"]'],
  [
    "googlecalendar",
    "Google Calendar",
    "scheduling & booking",
    '["OAUTH2"]',
    "49",
    '["https://www.googleapis.com/auth/calendar","https://www.googleapis.com/auth/calendar.events"]',
  ],
  [
    "youtube",
    "YouTube",
    "video & audio",
    '["OAUTH2"]',
    "51",
    '["https://www.googleapis.com/auth/youtube","https://www.googleapis.com/auth/youtube.channel-memberships.creator","https://www.googleapis.com/auth/youtube.force-ssl","https://www.googleapis.com/auth/youtube.readonly","https://www.googleapis.com/auth/youtube.upload","https://www.googleapis.com/auth/youtubepartner","https://www.googleapis.com/auth/youtubepartner-channel-audit"]',
  ],
  [
    "canva",
    "Canva",
    "images & design",
    '["OAUTH2"]',
    "48",
    '["asset:read","asset:write","brandtemplate:content:read","brandtemplate:meta:read","comment:read","comment:write","design:content:read","design:content:write","design:meta:read","folder:read","folder:write","folder:permission:write","profile:read"]',
  ],
  ["vimeo", "Vimeo", "video & audio", '["OAUTH2"]', "50", '["public","private"]'],
  [
    "facebook",
    "Facebook",
    "social media accounts",
    '["OAUTH2"]',
    "44",
    '["public_profile","email","pages_show_list","pages_read_engagement","pages_manage_posts","pages_manage_engagement","pages_read_user_content","pages_manage_metadata","pages_messaging","read_insights","business_management"]',
  ],
  [
    "d2lbrightspace",
    "D2L Brightspace",
    "education",
    '["OAUTH2"]',
    "45",
    '["quizzing:quizzes:delete","quizzing:quizzes:read","quizzing:quizzes:create"]',
  ],
  [
    "google_chat",
    "Google Chat",
    "productivity",
    '["OAUTH2"]',
    "46",
    '["https://www.googleapis.com/auth/chat.spaces.readonly","https://www.googleapis.com/auth/chat.spaces","https://www.googleapis.com/auth/chat.messages.readonly","https://www.googleapis.com/auth/chat.messages","https://www.googleapis.com/auth/chat.messages.create","https://www.googleapis.com/auth/chat.memberships.readonly","https://www.googleapis.com/auth/chat.memberships"]',
  ],
  [
    "railway_mcp",
    "Railway MCP",
    "developer tools",
    '["OAUTH2"]',
    "46",
    '["openid","profile","email","offline_access","workspace:member"]',
  ],
  [
    "zoom_chat",
    "Zoom Team Chat",
    "team chat",
    '["OAUTH2"]',
    "44",
    '["user:read:user","contact:read:list_contacts","team_chat:read:contact","team_chat:read:list_contacts","team_chat:read:channel","team_chat:read:list_user_channels","team_chat:read:list_members","team_chat:write:user_channel","team_chat:write:search_channels","team_chat:update:channel","team_chat:update:archive_channels","team_chat:delete:channel","team_chat:write:member","team_chat:write:members","team_chat:delete:member","team_chat:read:user_message","team_chat:read:list_user_messages","team_chat:read:thread_message","team_chat:write:user_message","team_chat:update:user_message","team_chat:update:message_status","team_chat:update:message_emoji","team_chat:delete:user_message","team_chat:read:list_pinned_messages"]',
  ],
  [
    "googledocs",
    "Google Docs",
    "documents",
    '["OAUTH2"]',
    "43",
    '["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/documents","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  ["trello", "Trello", "project management", '["OAUTH1"]', "329", '["read","write","account"]'],
  ["timely", "Timely", "time tracking software", '["OAUTH2"]', "41"],
  [
    "instagram",
    "Instagram",
    "social media accounts",
    '["OAUTH2"]',
    "36",
    '["instagram_business_basic","instagram_business_manage_messages","instagram_business_manage_comments","instagram_business_content_publish","instagram_business_manage_insights"]',
  ],
  [
    "typeform",
    "Typeform",
    "forms & surveys",
    '["OAUTH2"]',
    "35",
    '["accounts:read","forms:read","forms:write","images:read","images:write","themes:read","themes:write","responses:read","responses:write","webhooks:read","webhooks:write","workspaces:read","workspaces:write","offline"]',
  ],
  [
    "discord",
    "Discord",
    "team chat",
    '["OAUTH2"]',
    "28",
    '["identify","email","connections","guilds","guilds.join","guilds.members.read","messages.read","openid"]',
  ],
  [
    "googleads",
    "Google Ads",
    "ads & conversion",
    '["OAUTH2"]',
    "28",
    '["https://www.googleapis.com/auth/adwords"]',
  ],
  [
    "apaleo",
    "Apaleo",
    "scheduling & booking",
    '["OAUTH2"]',
    "29",
    '["offline_access","account.manage","account.suspend","accounting.read","authorizations.manage","authorizations.read","availability.manage","availability.read","charges.delete","companies.manage","companies.read","depositItems.manage","deposits.manage","deposits.read","folios.manage","folios.payment-with-charges","folios.read","invoices.manage","invoices.read","logs.read","maintenances.manage","maintenances.read","offer-index.read","offers.read"]',
  ],
  [
    "zoho_desk",
    "Zoho Desk",
    "crm",
    '["OAUTH2"]',
    "31",
    '["Desk.contacts.ALL","Desk.tickets.ALL","Desk.tasks.ALL","Desk.settings.ALL","Desk.events.ALL"]',
  ],
  [
    "epic_games",
    "Epic Games",
    "gaming",
    '["OAUTH2"]',
    "28",
    '["basic_profile","friends_list","presence"]',
  ],
  [
    "servicem8",
    "Servicem8",
    "scheduling & booking",
    '["OAUTH2"]',
    "28",
    '["staff_locations","staff_activity","publish_sms","publish_email","vendor","vendor_logo","vendor_email","read_locations","manage_locations","read_staff","manage_staff","read_customers","manage_customers","read_customer_contacts","manage_customer_contacts","read_jobs","manage_jobs","create_jobs","read_job_contacts","manage_job_contacts","read_job_materials","manage_job_materials","read_job_categories","manage_job_categories"]',
  ],
  [
    "linkedin_ads",
    "Linkedin Ads",
    "marketing",
    '["OAUTH2"]',
    "28",
    '["openid","profile","email","r_ads","rw_ads","r_ads_reporting","r_organization_social","w_organization_social","r_organization_admin","rw_organization_admin"]',
  ],
  [
    "linkedin",
    "LinkedIn",
    "social media accounts",
    '["OAUTH2"]',
    "24",
    '["openid","profile","w_member_social","email"]',
  ],
  ["webex", "Webex", "video conferencing", '["OAUTH2"]', "26", '["spark:all"]'],
  ["ynab", "YNAB", "accounting", '["OAUTH2"]', "27"],
  [
    "googlecontacts",
    "Googlecontacts",
    "productivity",
    '["OAUTH2"]',
    "24",
    '["https://www.googleapis.com/auth/contacts","https://www.googleapis.com/auth/contacts.other.readonly","https://www.googleapis.com/auth/directory.readonly","https://www.googleapis.com/auth/user.emails.read","https://www.googleapis.com/auth/userinfo.email","https://www.googleapis.com/auth/userinfo.profile"]',
  ],
  [
    "pinterest",
    "Pinterest",
    "social media accounts",
    '["OAUTH2"]',
    "24",
    '["boards:read","boards:read_secret","boards:write","boards:write_secret","pins:read","pins:read_secret","pins:write","pins:write_secret","user_accounts:read","user_accounts:write"]',
  ],
  [
    "salesforce_service_cloud",
    "Salesforce Service Cloud",
    "crm",
    '["OAUTH2"]',
    "24",
    '["full","refresh_token"]',
  ],
  [
    "reddit",
    "Reddit",
    "social media accounts",
    '["OAUTH2"]',
    "23",
    '["identity","read","vote","submit","flair","edit"]',
  ],
  [
    "yandex",
    "Yandex",
    "email",
    '["OAUTH2"]',
    "21",
    '["login:avatar","login:birthday","login:email","login:info","login:default_phone"]',
  ],
  [
    "mural",
    "Mural",
    "team collaboration",
    '["OAUTH2"]',
    "22",
    '["rooms:write","workspaces:write","murals:write","templates:write","rooms:read","users:read","workspaces:read","murals:read","identity:read","templates:read"]',
  ],
  [
    "box_mcp",
    "Box MCP",
    "model context protocol",
    '["OAUTH2"]',
    "21",
    '["root_readwrite","ai.readwrite"]',
  ],
  [
    "microsoft_todo",
    "Microsoft To Do",
    "task management",
    '["OAUTH2"]',
    "22",
    '["Tasks.ReadWrite","User.Read","offline_access","openid","profile"]',
  ],
  [
    "googletasks",
    "Google Tasks",
    "task management",
    '["OAUTH2"]',
    "18",
    '["https://www.googleapis.com/auth/tasks"]',
  ],
  ["snowflake", "Snowflake", "databases", '["OAUTH2"]', "17", '["refresh_token"]'],
  ["dynamics365", "Dynamics 365", "crm", '["OAUTH2"]', "16", '["offline_access"]'],
  [
    "zoominfo",
    "Zoominfo",
    "crm",
    '["OAUTH2"]',
    "16",
    '["api:account-summary:read","api:audience:manage","api:audience:read","api:audience-member:manage","api:audience-member:read","api:data:contact","api:data:company","api:data:scoops","api:data:news","api:data:intent"]',
  ],
  [
    "wakatime",
    "WakaTime",
    "time tracking software",
    '["OAUTH2"]',
    "17",
    '["read_summaries","read_summaries.editors","read_summaries.languages"]',
  ],
  [
    "googlemeet",
    "Google Meet",
    "video conferencing",
    '["OAUTH2"]',
    "15",
    '["https://www.googleapis.com/auth/meetings.space.created","https://www.googleapis.com/auth/meetings.space.settings"]',
  ],
  [
    "googlephotos",
    "Google Photos",
    "images & design",
    '["OAUTH2"]',
    "14",
    '["https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata","https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"]',
  ],
  [
    "boldsign",
    "Boldsign",
    "signatures",
    '["OAUTH2"]',
    "14",
    '["openid","profile","email","offline_access","BoldSign.Documents.All"]',
  ],
  [
    "zoho_mail",
    "Zoho Mail",
    "email",
    '["OAUTH2"]',
    "15",
    '["ZohoMail.partner.organization.ALL","ZohoMail.organization.accounts.ALL","ZohoMail.accounts.ALL","ZohoMail.organization.subscriptions.ALL","ZohoMail.organization.spam.ALL","ZohoMail.organization.domains.ALL","ZohoMail.organization.groups.ALL","ZohoMail.organization.policy.ALL","ZohoMail.organization.audit.ALL","ZohoMail.folders.ALL","ZohoMail.tags.ALL","ZohoMail.messages.ALL","ZohoMail.tasks.ALL","ZohoMail.links.ALL","ZohoMail.notes.ALL"]',
  ],
  ["exist", "Exist", "analytics", '["OAUTH2"]', "12", '["activity_read"]'],
  [
    "contacts_plus",
    "Contacts+",
    "contact management",
    '["OAUTH2"]',
    "13",
    '["account.read","contacts.read","contacts.write","tags.read","tags.write"]',
  ],
  [
    "google_admin",
    "Google Admin",
    "security & identity tools",
    '["OAUTH2"]',
    "14",
    '["https://www.googleapis.com/auth/admin.directory.user","https://www.googleapis.com/auth/admin.directory.user.readonly","https://www.googleapis.com/auth/admin.directory.user.alias","https://www.googleapis.com/auth/admin.directory.user.alias.readonly","https://www.googleapis.com/auth/admin.directory.group","https://www.googleapis.com/auth/admin.directory.group.readonly","https://www.googleapis.com/auth/admin.directory.group.member","https://www.googleapis.com/auth/admin.directory.group.member.readonly","https://www.googleapis.com/auth/admin.directory.orgunit","https://www.googleapis.com/auth/admin.directory.orgunit.readonly","https://www.googleapis.com/auth/admin.directory.domain","https://www.googleapis.com/auth/admin.directory.domain.readonly"]',
  ],
  ["ticktick", "Ticktick", "productivity", '["OAUTH2"]', "14", '["tasks:read","tasks:write"]'],
  [
    "vibe",
    "Vibe",
    "ads & conversion",
    '["OAUTH2","S2S_OAUTH2"]',
    "13",
    '["advertisers:read","campaigns:read","campaigns:write"]',
  ],
  [
    "freshbooks",
    "FreshBooks",
    "accounting",
    '["OAUTH2"]',
    "10",
    '["user:profile:read","user:projects:read","user:clients:read"]',
  ],
  [
    "buffer",
    "Buffer",
    "social media accounts",
    '["OAUTH2"]',
    "11",
    '["account:read","posts:read","posts:write","ideas:read","ideas:write","offline_access"]',
  ],
  [
    "google_search_console",
    "Google Search Console",
    "analytics",
    '["OAUTH2"]',
    "9",
    '["https://www.googleapis.com/auth/webmasters","https://www.googleapis.com/auth/webmasters.readonly","https://www.googleapis.com/auth/userinfo.profile","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  [
    "googleslides",
    "Google Slides",
    "documents",
    '["OAUTH2"]',
    "8",
    '["https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/presentations","https://www.googleapis.com/auth/userinfo.email"]',
  ],
  [
    "googleforms",
    "Googleforms",
    "productivity",
    '["OAUTH2"]',
    "10",
    '["https://www.googleapis.com/auth/forms.body","https://www.googleapis.com/auth/forms.body.readonly","https://www.googleapis.com/auth/forms.responses.readonly","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/drive.file","https://www.googleapis.com/auth/drive.readonly"]',
  ],
  [
    "notebook_lm",
    "NotebookLM",
    "ai assistants",
    '["OAUTH2"]',
    "11",
    '["https://www.googleapis.com/auth/discoveryengine.readwrite"]',
  ],
  [
    "pinterest_ads",
    "Pinterest Ads",
    "ads & conversion",
    '["OAUTH2"]',
    "10",
    '["ads:read","ads:write","user_accounts:read"]',
  ],
  [
    "tiktok",
    "Tiktok",
    "social media accounts",
    '["OAUTH2"]',
    "9",
    '["user.info.basic","user.info.profile","user.info.stats","video.list","video.upload","video.publish"]',
  ],
  ["wordpress_com", "WordPress.com", "content & files", '["OAUTH2"]', "10", '["global"]'],
  [
    "linkhut",
    "Linkhut",
    "bookmark managers",
    '["OAUTH2"]',
    "5",
    '["posts:read","posts:write","tags:read","tags:write"]',
  ],
  ["blackbaud", "Blackbaud", "fundraising", '["OAUTH2"]', "5", '["full"]'],
  [
    "gumroad",
    "Gumroad",
    "ecommerce",
    '["OAUTH2"]',
    "7",
    '["view_profile","edit_products","view_sales","mark_sales_as_shipped"]',
  ],
  [
    "google_data_studio",
    "Google Data Studio",
    "business intelligence",
    '["OAUTH2"]',
    "5",
    '["https://www.googleapis.com/auth/datastudio","openid","email","profile"]',
  ],
  [
    "lightspeed",
    "Lightspeed Retail X-Series",
    "commerce",
    '["OAUTH2"]',
    "7",
    '["retailer:read","payment_types:read","products:read","customers:read","sales:read"]',
  ],
  ["matterport", "Matterport", "developer tools", '["BASIC","OAUTH2"]', "6", '["ViewDetails"]'],
  ["elevenlabs", "ElevenLabs", "artificial intelligence", '["API_KEY"]', "155"],
  ["posthog", "PostHog", "analytics", '["API_KEY"]', "507"],
  ["shortcut", "Shortcut", "project management", '["API_KEY"]', "142"],
  ["freshdesk", "Freshdesk", "crm", '["API_KEY"]', "178"],
  ["sendgrid", "SendGrid", "transactional email", '["API_KEY"]', "364"],
  ["ashby", "Ashby", "hr talent & recruitment", '["API_KEY"]', "125"],
  ["datarobot", "DataRobot", "artificial intelligence", '["API_KEY"]', "840"],
  ["active_campaign", "ActiveCampaign", "marketing automation", '["API_KEY"]', "298"],
  ["active_trail", "ActiveTrail", "email newsletters", '["API_KEY"]', "159"],
  ["algolia", "Algolia", "developer tools", '["API_KEY"]', "133"],
  ["api_ninjas", "API Ninjas", "developer tools", '["API_KEY"]', "129"],
  ["benchmark_email", "Benchmark Email", "email newsletters", '["API_KEY"]', "298"],
  ["bookingmood", "Bookingmood", "scheduling & booking", '["API_KEY"]', "142"],
  ["bunnycdn", "BunnyCDN", "developer tools", '["API_KEY"]', "129"],
  ["centralstationcrm", "CentralStationCRM", "crm", '["API_KEY"]', "186"],
  ["chatbotkit", "Chatbotkit", "ai chatbots", '["API_KEY"]', "284"],
  ["cloudcart", "Cloudcart", "ecommerce", '["API_KEY"]', "150"],
  ["dnsfilter", "Dnsfilter", "security & identity tools", '["API_KEY"]', "170"],
  ["elevenreader", "Elevenreader", "artificial intelligence", '["API_KEY"]', "124"],
  ["fireberry", "Fireberry", "crm", '["API_KEY"]', "124"],
  ["gigasheet", "Gigasheet", "spreadsheets", '["API_KEY"]', "150"],
  ["gleap", "Gleap", "customer support", '["API_KEY"]', "179"],
  ["griptape", "Griptape", "artificial intelligence", '["API_KEY"]', "143"],
  ["hub_planner", "Hub Planner", "productivity", '["API_KEY"]', "122"],
  ["maxio", "Maxio", "commerce", '["API_KEY"]', "177"],
  ["metabase", "Metabase", "business intelligence", '["API_KEY"]', "194"],
  ["moco", "Moco", "project management", '["API_KEY"]', "218"],
  ["nasa", "Nasa", "developer tools", '["API_KEY"]', "136"],
  ["new_relic", "New Relic", "server monitoring", '["API_KEY"]', "159"],
  ["openai", "OpenAI", "artificial intelligence", '["API_KEY"]', "126"],
  ["postman", "Postman", "developer tools", '["API_KEY"]', "135"],
  ["rentman", "Rentman", "productivity", '["API_KEY"]', "130"],
  ["repairshopr", "RepairShopr", "crm", '["API_KEY"]', "147"],
  ["safetyculture", "SafetyCulture", "forms & surveys", '["API_KEY"]', "255"],
  ["simla_com", "Simla.com", "crm", '["API_KEY"]', "141"],
  ["tave", "Tave", "crm", '["API_KEY"]', "129"],
  ["turbot_pipes", "Turbot Pipes", "developer tools", '["API_KEY"]', "170"],
  ["affinda", "Affinda", "artificial intelligence", '["API_KEY"]', "119"],
  ["better_stack", "Better Stack", "server monitoring", '["API_KEY"]', "117"],
  ["braze", "Braze", "marketing automation", '["API_KEY"]', "119"],
  ["celigo", "Celigo", "developer tools", '["API_KEY"]', "117"],
  ["faraday", "Faraday", "artificial intelligence", '["API_KEY"]', "117"],
  ["instantly", "Instantly", "drip emails", '["API_KEY"]', "117"],
  ["iterable", "Iterable", "marketing", '["API_KEY"]', "116"],
  ["apify", "Apify", "ai web scraping", '["API_KEY"]', "113"],
  ["paystack", "Paystack", "payment processing", '["API_KEY"]', "112"],
  ["sevdesk", "Sevdesk", "accounting", '["API_KEY"]', "115"],
  ["neon", "Neon", "databases", '["API_KEY"]', "110"],
  ["coda", "Coda", "productivity", '["API_KEY"]', "110"],
  ["cloudinary", "Cloudinary", "images & design", '["API_KEY"]', "109"],
  ["baselinker", "Baselinker", "ecommerce", '["API_KEY"]', "106"],
  ["hookdeck", "Hookdeck", "developer tools", '["API_KEY"]', "105"],
  ["twelve_data", "Twelve Data", "analytics", '["API_KEY"]', "107"],
  ["digicert", "Digicert", "security & identity tools", '["API_KEY"]', "101"],
  ["ngrok", "Ngrok", "developer tools", '["API_KEY"]', "102"],
  ["outline", "Outline", "productivity", '["API_KEY"]', "101"],
  ["agencyzoom", "AgencyZoom", "crm", '["API_KEY","BASIC_WITH_JWT"]', "99"],
  ["domotz_mcp", "Domotz MCP", "model context protocol", '["API_KEY"]', "99"],
  ["here", "Here", "developer tools", '["API_KEY"]', "99"],
  ["route4me", "Route4me", "project management", '["API_KEY"]', "97"],
  ["mixmax", "Mixmax", "email", '["API_KEY"]', "94"],
  ["render", "Render", "developer tools", '["API_KEY"]', "95"],
  ["elastic_email", "Elastic Email", "email", '["API_KEY"]', "91"],
  ["esputnik", "Esputnik", "marketing automation", '["API_KEY"]', "89"],
  ["gosquared", "Gosquared", "analytics", '["API_KEY"]', "90"],
  ["penpot", "Penpot", "images & design", '["API_KEY"]', "90"],
  ["polygon", "Polygon", "analytics", '["API_KEY"]', "90"],
  ["swarmsyncai", "Swarmsyncai", "developer tools", '["API_KEY"]', "91"],
  ["mailerlite", "MailerLite", "email newsletters", '["API_KEY"]', "86"],
  ["incident_io", "incident.io", "developer tools", '["API_KEY"]', "86"],
  ["rocketlane", "Rocketlane", "project management", '["API_KEY"]', "81"],
  ["census_bureau", "Census Bureau", "analytics", '["API_KEY"]', "81"],
  ["tomtom", "Tomtom", "developer tools", '["API_KEY"]', "82"],
  ["agenty", "Agenty", "ai web scraping", '["API_KEY"]', "79"],
  ["documenso", "Documenso", "signatures", '["API_KEY"]', "77"],
  ["etermin", "Etermin", "scheduling & booking", '["API_KEY"]', "78"],
  ["kadoa", "Kadoa", "ai web scraping", '["API_KEY"]', "77"],
  ["quaderno", "Quaderno", "taxes", '["API_KEY"]', "76"],
  ["synthflow_ai", "Synthflow AI", "ai agents", '["API_KEY"]', "79"],
  ["content_studio", "ContentStudio", "social media marketing", '["API_KEY"]', "72"],
  ["heygen", "HeyGen", "artificial intelligence", '["API_KEY"]', "71"],
  ["encodian", "Encodian", "documents", '["API_KEY"]', "69"],
  ["habitica", "Habitica", "productivity", '["API_KEY"]', "70"],
  ["nextdns", "Nextdns", "security & identity tools", '["API_KEY"]', "68"],
  ["paradym", "Paradym", "security & identity tools", '["API_KEY"]', "69"],
  ["persona", "Persona", "security & identity tools", '["API_KEY"]', "69"],
  ["retellai", "Retell AI", "artificial intelligence", '["API_KEY"]', "67"],
  ["altoviz", "Altoviz", "accounting", '["API_KEY"]', "67"],
  ["anchor_browser", "Anchor Browser", "ai agents", '["API_KEY"]', "64"],
  ["api_sports", "API-Sports", "developer tools", '["API_KEY"]', "67"],
  ["circleci", "CircleCI", "developer tools", '["API_KEY"]', "65"],
  ["hashnode", "Hashnode", "developer tools", '["API_KEY"]', "67"],
  ["insighto_ai", "Insighto.ai", "ai chatbots", '["API_KEY"]', "65"],
];
