/** Operator-facing copy; the technical route names remain stable. */
const en = {
  title: "Workspace control",
  description: "Run coordinated tasks, inspect results, and manage project tools.",
  work: "Work",
  inspect: "Inspect",
  manage: "Manage",
  navigation: "Workspace tools",
  chooseTool: "Tool",
  swarm: "Run a task",
  ledger: "Activity",
  mailbox: "Agent messages",
  loop: "Run health",
  topology: "Code structure",
  guardian: "Command safety",
  consensus: "Reviews & handoffs",
  context: "Context usage",
  memory: "Memory",
  keys: "API keys",
  flamegraph: "Trace performance",
  snapshots: "Snapshots",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  close: "Close",
  projectRequired: "Select a project to use workspace tools.",
  connected: "Live updates",
  polling: "Periodic updates",
  connecting: "Connecting…",
  offline: "Disconnected — displayed data may be out of date.",
  goal: "What should the agents do?",
  goalHint:
    "Describe the outcome and how it should be checked. This runs agents in the selected project and may change workspace files or incur model costs.",
  goalPlaceholder: "For example: fix the failing tests and explain what changed.",
  launch: "Run task",
  running: "Task running…",
  taskSuccess: "Task finished. Review its activity below.",
  agents: "Agents",
  noAgents: "No agent activity reported yet. Run a task to begin.",
  task: "Current task",
  completed: "Completed tasks",
  channels: "Coordination",
  noChannels: "No coordination channels reported.",
  idle: "Idle",
  active: "Working",
  waiting_approval: "Needs approval",
  handoff: "Handing off",
  queued: "Queued",
  runningStatus: "Running",
  completedStatus: "Completed",
  interrupted: "Interrupted",
  failed: "Failed",
  history: "Recorded turns",
  historyHint: "Project-level execution history. Open Context usage to inspect a conversation.",
  noHistory: "No recorded turns yet.",
  outcome: "Outcome",
  duration: "Duration",
  records: "Stream records",
  sequence: "Sequence",
  recipient: "Recipient",
  chooseRecipient: "Choose an agent",
  message: "Message",
  messageHint: "Send an instruction to an agent reported by this project's runtime.",
  send: "Send message",
  sending: "Sending…",
  sent: "Message queued.",
  noMailbox: "No mailbox activity reported.",
  queue: "Queued",
  replies: "Pending replies",
  lease: "Lease",
  healthHint:
    "Recorded failures are not a circuit-breaker state. Runtime telemetry does not currently report whether a breaker has stopped execution.",
  failures: "Failed recorded turns",
  protection: "Execution protection",
  unknown: "Not reported",
  reviewSafety: "Review command safety",
  lastUpdate: "Last update",
  notReceived: "Not received",
  noTask: "No active task reported",
  session: "Conversation context",
};
type Copy = { [K in keyof typeof en]: string };
const zh: Copy = {
  title: "工作区控制",
  description: "运行协作任务、检查结果并管理项目工具。",
  work: "工作",
  inspect: "检查",
  manage: "管理",
  navigation: "工作区工具",
  chooseTool: "工具",
  swarm: "运行任务",
  ledger: "活动记录",
  mailbox: "智能体消息",
  loop: "运行状态",
  topology: "代码结构",
  guardian: "命令安全",
  consensus: "审查与交接",
  context: "上下文用量",
  memory: "记忆",
  keys: "API 密钥",
  flamegraph: "执行性能",
  snapshots: "快照",
  refresh: "刷新",
  refreshing: "正在刷新…",
  close: "关闭",
  projectRequired: "请选择项目以使用工作区工具。",
  connected: "实时更新",
  polling: "定期更新",
  connecting: "正在连接…",
  offline: "连接已断开，显示的数据可能已过时。",
  goal: "需要智能体完成什么？",
  goalHint: "描述预期结果以及验证方式。任务将在所选项目中运行，可能修改工作区文件并产生模型费用。",
  goalPlaceholder: "例如：修复失败的测试并解释修改内容。",
  launch: "运行任务",
  running: "任务运行中…",
  taskSuccess: "任务已结束，请检查活动记录。",
  agents: "智能体",
  noAgents: "暂无智能体活动。运行任务以开始。",
  task: "当前任务",
  completed: "已完成任务",
  channels: "协作关系",
  noChannels: "暂无协作关系。",
  idle: "空闲",
  active: "工作中",
  waiting_approval: "等待审批",
  handoff: "交接中",
  queued: "排队中",
  runningStatus: "运行中",
  completedStatus: "已完成",
  interrupted: "已中断",
  failed: "失败",
  history: "执行记录",
  historyHint: "项目级执行历史。可打开“上下文用量”检查某个会话。",
  noHistory: "暂无执行记录。",
  outcome: "结果",
  duration: "耗时",
  records: "流记录数",
  sequence: "序号",
  recipient: "接收者",
  chooseRecipient: "选择智能体",
  message: "消息",
  messageHint: "向当前项目运行时报告的智能体发送指令。",
  send: "发送消息",
  sending: "发送中…",
  sent: "消息已加入队列。",
  noMailbox: "暂无信箱活动。",
  queue: "排队消息",
  replies: "待回复",
  lease: "租约",
  healthHint: "执行失败数量不代表熔断器状态。当前运行时遥测未报告熔断器是否已停止执行。",
  failures: "已记录的失败次数",
  protection: "执行保护",
  unknown: "未报告",
  reviewSafety: "检查命令安全",
  lastUpdate: "最近更新",
  notReceived: "尚未收到",
  noTask: "未报告活动任务",
  session: "会话上下文",
};
export function cockpitCopy(locale: "en" | "zh"): Copy {
  return locale === "zh" ? zh : en;
}
export const cockpitGroups = [
  { key: "work", tools: ["swarm", "ledger", "mailbox", "consensus"] },
  { key: "inspect", tools: ["topology", "context", "flamegraph", "loop"] },
  { key: "manage", tools: ["memory", "keys", "guardian", "snapshots"] },
] as const;
export type CockpitTool = (typeof cockpitGroups)[number]["tools"][number];
export function isCockpitTool(value: string): value is CockpitTool {
  return cockpitGroups.some((group) => group.tools.some((tool) => tool === value));
}
